collections_dir: _collections/

collections:
  slides:
    output: false

# sass:
#     load_paths:
#         - _sass
#         - node_modules

# defaults:
#   - scope:
#       path: ""
#     values:
#       layout: "default"

include: ["node_modules"]
exclude: []

slidesList: [
  "title-slide",
  "course-goals",
  "why-bitcoin",
  "financial-freedom",
  "satoshi-nakamoto",
  "global-financial-crisis",
  "bitcoin-solved-problems",
  "investment_bank_collapse.jpg",
  "subprime-mortgage-crisis",
  "too-big-to-fail",
  "digital-uniqueness",
  "history-of-cryptocurrency",
  "digital-currency-web",
  "internet-cash",
  "digital-currency-experiments",
  "paypal-launch",
  "central-server",
  "decentralized-network",
  "defining-bitcoin",
  "values-behind-blockchain",
  "bitcoin-money",
  "most-currency-digital",
  "functions-of-money",
  "bitcoin-pizza-day",
  "early-bitcoin-use",
  "bitcoin-transaction-process",
  "its-software",
  "tx-flow",
  "data-signing",
  "broadcasting-transaction",
  "validation",
  "mempool-before-mining",
  "block-inclusion",
  "online-requirements",
  "mining-mechanics",
  "inside-a-miner",
  "network-consensus",
  "block-example",
  "which-transactions-included",
  "block-joins-chain",
  "mining-profitability",
  "transaction-fees",
  "where-fees-go",
  "token-creation-cycle",
  "create-block",
  "generate-cryptocurrency",
  "exchange-token-resources",
  "transaction-fee-generated",
  "bitcoin-issuance-schedule",
  "programmable-money",
  "blockchains-beyond-bitcoin",
  "ethereum-more-than-money",
  "smart-contracts",
  "transaction-time",
  "blockchains-not-free",
  "creditcards-vs-crypto",
  "keeping-crypto-secure",
  "transparency-privacy",
  "address-reuse-privacy",
  "what-are-wallets",
  "public-private-keys",
  "seed-phrases",
  "custodial-noncustodial",
  "restoring-wallet",
  "crypto-wallets",
  "wallet-types",
  "hardware-wallets",
  "software-wallets",
  "web-wallets",
  "paper-wallets",
  "inspecting-transaction",
  "transaction-status",
  "how-blockchains-differ",
  "how-blockchains-secured",
  "incentive-engineering",
  "hostile-attack",
  "decentralized-security",
  "buy-with-cryptocurrency",
  "ecommerce",
  "companies-accepting-cryptocurrency",
  "money-without-borders",
  "trading",
  "holding",
  "future-vision-use",
  "blockchain-business",
  "provenance-supply-chain",
  "certifications-credentials",
  "accounting",
  "banking",
  "nonprofit",
  "digital-identity",
  "blockchains-imperfect",
  "privacy",
  "scaling-global-usage",
  "unanswered-questions",
  "need-better-tools",
  "worth-using",
  "modern-challanges",
  "technology-tools-defenses",
  "web3",
  "course-summary",
  "questions-and-answers",
  "0-how-to-join-us" ]