collections_dir: _collections/

collections:
  slides:
    output: false

# sass:
#     load_paths:
#         - _sass
#         - node_modules

# defaults:
#   - scope:
#       path: ""
#     values:
#       layout: "default"

include: ["node_modules"]
exclude: []

slidesList: [
  "title-slide",
  "course-goals",
  "intro",
  "properties-of-defi",
  "openness",
  "modular",
  "decentralized",
  "banks-bailed-out",
  "you-can-be-the-bank",
  "getting-to-defi",
  "the-limitations-of-bitcoin",
  "bitcoins-purpose",
  "bitcoins-purpose-2",
  "smart-contracts-introduced",
  "what-are-smart-contracts",
  "technological-limitations",
  "altcoins-address-bitcoins-deficiencies",
  "colored-coins",
  "mastercoin",
  "ethereum",
  "ethereum-new-paradigm",
  "motivations-for-creating-ethereum",
  "what-is-ethereum",
  "evm",
  "evm-2",
  "block-time-decreased",
  "ethereum-and-metamask",
  "adding-ether-to-metamask",
  "transactions-with-ethereum",
  "troubleshooting-stuck-transactions",
  "ethereum-and-defi",
  "early-dapps",
  "the-lighthouse-crowdfunding-issue",
  "ethereum-and-crowdfunding",
  "nfts-colored-coins-erc-721",
  "icos",
  "stablecoins-from-tether-dai",
  "stablecoins-and-defi",
  "what-are-stablecoins",
  "volatility-and-cryptocurrency-markets",
  "why-stablecoins",
  "stablecoins-markets-and-financial-services",
  "different-types-of-stablecoins",
  "currency-backed",
  "create-block",
  "asset-backed",
  "leveraged-by-cryptocurrency",
  "converting-eth-to-dai",
  "properties-of-defi",
  "decentralized",
  "open-to-all",
  "censorship-resistant",
  "banking-the-unbanked",
  "financial",
  "yield-farming",
  "liquidity-pools",
  "adding-a-pair",
  "adding-a-pair-2",
  "technological",
  "open-source",
  "using-crypto-security",
  "new-innovations",
  "defis-applications",
  "dexs",
  "removing-liquidity",
  "savings",
  "lending",
  "wallets",
  "asset-management",
  "defi-limitations",
  "running-at-ethereums-pace",
  "scaling",
  "banks-and-market-domination",
  "lack-of-liquidity",
  "ease-of-use",
  "possible-solutions",
  "future-of-defi",
  "what-is-next",
  "course-summary",
  "questions-and-answers",
  "how-to-join-us" ]
